### PR TITLE
axioms for term definitions

### PR DESCRIPTION
**Pull request by meghalithic**
issue #12

### CODE REVIEW

**Comment by hlapp** [comment]
Great, nice @megbalk! Can you say what the ` | ` syntax should translate to? Such as in `'anatomical point' | 'part of' some  ...`

**Comment by meghalithic** [comment]
@hlapp "|" is to signify it'd be a separate subclass, so there would be multiple subclass axioms.

**Comment by hlapp** [comment]
So are semantics 'and' or 'or'? I suspect you don't think you mean to say `'anatomical point' or 'part of' some ...`, but probably `'anatomical point' and 'part of' some ...` in which case the ` | ` can (and arguably should) just be substituted by ` and ` (perhaps with proper parenthesizing the following expression).

**Comment by meghalithic** [comment]
This is how it would look in the ontology, but the format of the sheet doesn't allow for this. I use the | as a signal that it is a separate subclass.

```
logical_axioms:
  - axiom_type: subClassOf
    text: "'anatomical point'"

  - axiom_type: subClassOf
    text: "'part of' some ('in posterior side of' some 'eye')"
```

**Pull request merged**
