### PR TITLE
Workflows analysis

### PR DESCRIPTION
**Pull request by thibaulttabarin**
I split the different step in its own Snakefile
Snake_download 
Snake_metadata
Snake_crop
Snake_seg
Snake_morph

There are 2 SLURM_Snake
SLURM_Snake_download that takes config file INPUTCSV, therefore this one is used only by Snake_download
SLURM_Snake_generic works with other Snake_*** (metadata, crop, seg, morpho)

There is a README.md with the usage syntax.
This folder is what I have been using to test during development and to process the data step by step, this could be useful to other!

### CODE REVIEW

**Comment by johnbradley** [comment]
It looks like most of the logic in the various Snake_download, Snake_metadate, Snake_crop, etc files are just bits copied out of BGNN_Snakemake. For example:

https://github.com/hdr-bgnn/minnowTraits/blob/f567c720f2020b01c9543d24b0ff628d0af53e8c/Workflows_minnows/Step_by_step/Snake_download#L7-L19
vs
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/502d285fe89374926cfe1b7d4240388d9946c27e/Snakefile#L6-L18
```
LIST = config['list']


print(f"your are using this list {LIST}")


df = pd.read_csv(f'{LIST}')
split_df = df['original_file_name'].str.split('\\.', expand=True)
split_df.columns=['original_file_name','2']
samples_df = df.drop(columns=['original_file_name'])
df = pd.merge(split_df['original_file_name'],samples_df, how="left", left_index=True, right_index=True)
samples_df = df.set_index('original_file_name', drop=False)


NAMES = list(samples_df['original_file_name'])
NAMES = [os.path.splitext(name)[0] for name in NAMES]
```
---

Are we abandoning the use of https://github.com/hdr-bgnn/BGNN_Snakemake as part of this project?

**Comment by thibaulttabarin** [comment]
@johnbradley 
could you review this and make the change for the export SBATCH_ACCOUNT=$SLURM_JOB_ACCOUNT in SLURM_Snake_download and  SLURM_Snake_generic you have suggested.
Cheers

**Comment by johnbradley** [comment]
@thibaulttabarin Are we abandoning the use of https://github.com/hdr-bgnn/BGNN_Snakemake for Minnow_Traits? Why not make these fixes/re-organization in the BGNN_Snakemake repo?

**Comment by thibaulttabarin** [comment]
I don't know.. good question...
Well, my understanding was that BGNN_snakemake would be a generic version for the workflow, but for each specific project we would put the specific workflow of the project (read as paper) on project repository.

**Pull request closed without merging**
