### PR TITLE
Automate running the pipeline

### LINKED ISSUE #3: Automate running the entire process
Create a method for a user to run the entire process.

### LINKED ISSUE #4: Improve portability by removing hard coded paths
Some of the scripts have hard coded paths. For example:

https://github.com/hdr-bgnn/minnowTraits/blob/686113ec48bff0a990314b23720e299e237871f9/Scripts/selectionCriteriaSegmentedImages.R#L13-L14
Update the scripts removing the hard coded paths.

### PR DESCRIPTION
**Pull request by johnbradley**
Creating this draft PR to get help on an error creating the plots.
When complete this PR will allow a user to run `sbatch run-pipeline.sh` to run the entire pipeline.
This includes the two R Scripts in this repo as well as running BGNN_Snakemake.

The code is still in a WIP state, but feedback is still welcomed.

Fixes #3
Fixes #4

### CODE REVIEW

**Comment by johnbradley** [comment]
When running selectionCriteriaSegmentedImages.R I receive the following error:
```
Error in heatmap(stats.sp.trim, labRow = rownames(stats.sp.trim), labCol = colnames(stats.sp.trim),  : 
  'x' must have at least 2 rows and 2 columns
Execution halted
```
https://github.com/hdr-bgnn/minnowTraits/blob/20a4ae13a4078971bbcd45b792424420f3bc7920/Scripts/selectionCriteriaSegmentedImages.R#L210-L213

---

After debugging I noticed the **presence.absence.matrix.csv** file created was much smaller than the one in the repo:[Files/presence.absence.matrix.csv](https://github.com/hdr-bgnn/minnowTraits/blob/main/Files/presence.absence.matrix.csv). 
My generated file:
```
$ wc -l results/presence.absence.matrix.csv 
448 results/presence.absence.matrix.csv
```
The one already in the repo:
```
$ wc -l Files/presence.absence.matrix.csv 
6298 Files/presence.absence.matrix.csv
```

---

I think my problem is I am running BGNN_Snakemake with the wrong input CSV and not generating enough `Morphology/Presence/*.json" files.

@megbalk or @thibaulttabarin 
Should I run  snakemake with "minnow.filtered.from.imagequalitymetadata_25Jul2022.csv" or "burress.minnow.sp.filtered.from.imagequalitymetadata_25Jul2022.csv" or perhaps another file?

**Comment by thibaulttabarin** [comment]
minnow.filtered.from.imagequalitymetadata_25Jul2022.csv will a fair amount of time (I think it took me 5 h with 28 cores)
But I am almost done with it using the most updated version of the different parts
it should be finished in the afternoon.

**Comment by thibaulttabarin** [comment]
have you try to use /fs/ess/PAS2136/BGNN/Test_lab

**Comment by johnbradley** [comment]
> have you try to use /fs/ess/PAS2136/BGNN/Test_lab

@thibaulttabarin It looks like there are only 10 json Morphology/Presence files within that directory.
```
$ ls /fs/ess/PAS2136/BGNN/Test_lab/Morphology/Presence/*  | wc -l
10
```
Is this all that's needed for the ending scripts?

**Comment by johnbradley** [comment]
I figured out the problem I was having with `selectionCriteriaSegmentedImages.R`. The bug was due to my changes to remove the hard coded paths. The directory name was making it into the `file.name` field and this prevented looking up metadata. The following line fixed the problem:
https://github.com/hdr-bgnn/Minnow_Traits/blob/8bdee8fa0a111259259a36790d6de4e7840f9b1d/Scripts/selectionCriteriaSegmentedImages.R#L36-L38

**Comment by johnbradley** [comment]
I'm going to close this PR and create a simpler version of these changes once issue #4 is resolved.

**Pull request closed without merging**
